apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: 
    app: backend
  name: backend-role
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - list
      - get
      - watch
      # - delete
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: 
    app: backend
  name: backend-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backend-role
subjects:
  - kind: ServiceAccount
    name: backend
    namespace: default
