apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      app: dice
  template:
    metadata:
      labels:
        tier: backend
        app: dice
    spec:
      containers:
      - name: backend
        image: hasnainzaib/abc
        env:
          - name: NAME
            valueFrom:
              secretKeyRef:
                name: backend
                key: name
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend
                key: password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 3
          failureThreshold: 2
          periodSeconds: 3
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1      
        ports:
        - containerPort: 8080
          name: tcp
        volumeMounts:
        - name: details-vol
          mountPath: /user
      volumes:
      - name: details-vol
        configMap:
          name: backend
          items:
          - key: details.txt
            path: details.txt
      serviceAccountName: backend


---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    tier: backend
    app: dice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: backend
  name: backend